version: '3'
services:
  db:
    platform: linux/arm64/v8
    image: mariadb:10.2
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: api_training
    ports:
      - "3306:3306" # 3306のポートがきたら、3306のポートを使う
    volumes:
      - db-store:/var/lib/mysql/
      - ./logs:/var/log/mysql
volumes:
  db-store: