version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: api_training
    ports:
      - 3306:3306 # 3306のポートがきたら、3306のポートを使う
    volumes:
      - ./docker/tmp/mysql:/var/lib/mysql