server:
  port: 8080
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_training
    username: root
    password: root
    jpa:
      properties:
        hibernate:
          ## Hibernate Properties
          # The SQL dialect makes Hibernate generate better SQL for the chosen database
          # Hibernate ddl auto (create, create-drop, validate, update)
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          ddl-auto: update
# setting for mapping DB columns by snake-style and Java properties by camel-case-style
mybatis:
  configuration:
    map-underscore-to-camel-case: true