# Web
server:
  port: 8080
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/api_training
    username: root
    password: password
    driverClassName: org.mariadb.jdbc.Driver
# setting for mapping DB columns by snake-style and Java properties by camel-case-style
mybatis:
  configuration:
    map-underscore-to-camel-case: true
jackson:
  serialization:
    write-dates-as-timestamps: false
    write-durations-as-timestamps: true
e_stat:
  api:
    json:
      REGION_INFO_PATH: https://dashboard.e-stat.go.jp/api/1.0/Json/getData?Lang=JP